name: "[release] Build and Push Container Images"

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

# concurrency:
  # group: "ci-main"
  # cancel-in-progress: false

permissions:
  contents: read

jobs:
  # update-binaries:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build release
  #     run: |
  #       cd ./security-goat && make clean && make release 

  ghcrio:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ghcr.io/andersonbosa/publish-packages/security-goat

      - name: Login to GHCR
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to ghcr.io registry
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./security-goat/.
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }},ghcr.io/${{ github.repository }}:latest

  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push to hub.docker.com registry
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./security-goat/.
          push: true
          tags: t4inha/security-goat:latest
