name: "[security] Gosec Scan"

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]

# concurrency:
#   group: "ci-main"
#   cancel-in-progress: false

jobs:
  go-sec_scan:
    name: Security Goat GoSec Scan
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Project
        id: checkout_project
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Run Gosec Security Scanner
        id: run_gosec
        uses: securego/gosec@master
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: "-no-fail -fmt json -out results.json ./..."

      - name: Archive GoSec Scan Results
        id: archive_gosec_results
        uses: actions/upload-artifact@v4
        with:
          name: results.json
          path: results.json
